/**
 * Generates per-beat MP3s under `remotion/public/voice/beat-01.mp3` … from `SHOWCASE_BEATS`
 * in `remotion/src/demo-timeline.ts` (synced with Playwright). Also writes
 * `remotion/src/voice-beat-durations.generated.ts` with measured MP3 lengths so Remotion beats are
 * long enough for the audio (see `beatEffectiveDurationSec`).
 *
 * Optional: set `SHOWCASE_VOICE_NARRATIONS_JSON` to a JSON file mapping `DemoTimelinePhaseId` →
 * narration string (see `replay/.generated/voice-narrations.json` from `pnpm showcase:outline`).
 */
import { config } from "dotenv";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { parseFile } from "music-metadata";
import {
  SHOWCASE_BEATS,
  type DemoTimelinePhaseId,
} from "../remotion/src/demo-timeline";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
config({ path: join(root, ".env") });

const VOICE_DIR = join(root, "remotion/public/voice");

function resolveNarrationsPath(): string | null {
  const raw = process.env.SHOWCASE_VOICE_NARRATIONS_JSON?.trim();
  if (!raw) return null;
  return raw.startsWith("/") ? raw : resolve(root, raw);
}

function loadNarrationOverrides():
  | Partial<Record<DemoTimelinePhaseId, string>>
  | null {
  const p = resolveNarrationsPath();
  if (!p || !existsSync(p)) {
    if (process.env.SHOWCASE_VOICE_NARRATIONS_JSON?.trim()) {
      console.warn(`voiceover: file not found: ${p}`);
    }
    return null;
  }
  const data = JSON.parse(readFileSync(p, "utf-8")) as Record<string, string>;
  console.log(`voiceover: using narration overrides from ${p}`);
  return data;
}

async function ttsOne(
  apiKey: string,
  text: string,
  voiceId: string
): Promise<Buffer> {
  const res = await fetch(
    `https://api.elevenlabs.io/v1/text-to-speech/${voiceId}`,
    {
      method: "POST",
      headers: {
        "xi-api-key": apiKey,
        "Content-Type": "application/json",
        Accept: "audio/mpeg",
      },
      body: JSON.stringify({
        text,
        model_id: "eleven_multilingual_v2",
      }),
    }
  );

  if (!res.ok) {
    const err = await res.text();
    const hint =
      res.status === 402
        ? " (Library/premium voices often require a paid ElevenLabs plan for API use; try a voice that works on your tier or upgrade.)"
        : "";
    throw new Error(`ElevenLabs HTTP ${res.status}: ${err}${hint}`);
  }

  return Buffer.from(await res.arrayBuffer());
}

async function main() {
  const key = process.env.ELEVENLABS_API_KEY;
  const voiceId =
    process.env.ELEVENLABS_VOICE_ID ?? "3TStB8f3X3To0Uj5R7RK";
  if (!key) {
    console.error("Missing ELEVENLABS_API_KEY (set in .env or the environment).");
    process.exit(1);
  }

  mkdirSync(VOICE_DIR, { recursive: true });

  const overrides = loadNarrationOverrides();

  for (let i = 0; i < SHOWCASE_BEATS.length; i++) {
    const beat = SHOWCASE_BEATS[i];
    const n = String(i + 1).padStart(2, "0");
    const out = join(VOICE_DIR, `beat-${n}.mp3`);
    const text =
      overrides?.[beat.phase]?.trim() || beat.narration;
    const buf = await ttsOne(key, text, voiceId);
    writeFileSync(out, buf);
    console.log(`Wrote ${out} (${buf.length} bytes) [${beat.phase}]`);
    if (i < SHOWCASE_BEATS.length - 1) {
      await new Promise((r) => setTimeout(r, 400));
    }
  }

  console.log(`Done: ${SHOWCASE_BEATS.length} beats in ${VOICE_DIR}`);

  const durations: number[] = [];
  for (let i = 0; i < SHOWCASE_BEATS.length; i++) {
    const n = String(i + 1).padStart(2, "0");
    const p = join(VOICE_DIR, `beat-${n}.mp3`);
    const meta = await parseFile(p);
    const sec = meta.format.duration;
    durations.push(
      typeof sec === "number" && Number.isFinite(sec) && sec > 0 ? sec : 0,
    );
  }

  const genPath = join(root, "remotion/src/voice-beat-durations.generated.ts");
  const genBody =
    "/**\n" +
    " * Auto-generated by scripts/generate-voiceover.ts — MP3 durations (seconds).\n" +
    " * Re-run after regenerating voice files.\n" +
    " */\n" +
    `export const VOICE_BEAT_DURATION_SEC: readonly number[] = [${durations
      .map((d) => (d > 0 ? d.toFixed(4) : "0"))
      .join(", ")}] as const;\n`;
  writeFileSync(genPath, genBody);
  console.log(`Wrote ${genPath}`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
