/**
 * Auto-generated by scripts/generate-voiceover.ts — MP3 durations (seconds).
 * Re-run after regenerating voice files.
 */
export const VOICE_BEAT_DURATION_SEC: readonly number[] = [11.1282, 9.3257, 9.9265, 10.3967, 11.6506, 11.7029, 9.6392, 8.1763, 5.2767] as const;
